# These are the people that help fund TargetDash development

# GitHub Sponsors
github: [chzchzchz]

# Patreon
patreon: targetdash

# Open Collective
open_collective: targetdash

# Ko-Fi
kofi: targetdash

# Tidelift
tidelift: npmp/@targetdash/ai-crm

# Community Bridge
community_bridge: targetdash

# Liberapay
liberapay: targetdash

# IssueHunt
issuehunt: targetdash/ai-crm

# Otechie
otechie: targetdash

# Custom URL
custom: ["https://targetdash.com/sponsor"]
